spring:
  application:
    name: zipkin-client-one
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

