spring:
  application:
    name: zipkin-client-two
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8094

eureka:
  client:
    service-url:
      defualtZone: http://localhost:8081/eureka/