spring:
  application:
    name: zipkin-client-two
  zipkin:
    base-url: http://localhost:9411   # 指定 zipkin server 的地址
server:
  port: 8094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
